### ISSUE TITLE
Sidebery closes after dragging a tab

### ISSUE THREAD

**Issue by konfitti** [Naezr/ShyFox#64] opened 2024-06-26 15:37 UTC
https://github.com/Naezr/ShyFox/assets/69910686/dcdd9a97-e95e-48ea-bc3c-b26889058986

**Comment by Naezr** [comment] 2024-06-27 04:48
Known issue. I don't know how to fix it. For some reason on Linux the cursor holding something doesn't activate the `:hover` css selector. On Windows it works as it should

**Comment by Naezr** [comment] 2024-06-27 07:33
[Запись экрана от 2024-06-27 14-28-54.webm](https://github.com/Naezr/ShyFox/assets/95460152/c3dd5c10-776b-45b7-8628-3ab24c2ece76)

**Comment by SourCreamKun** [comment] 2024-06-27 13:57
I think the issue was when you separate a tab _to a new window_ sidebery closes, in windows it closes too.
It also is closed when you open a new window from firefox shortcut on taskbar

**Comment by Naezr** [comment] 2024-06-27 14:25
The fact is that the logic of this is different on Windows and Linux, although the css code is the same everywhere.

**Comment by Duder963** [comment] 2024-06-28 04:44
That's odd. I've been using this on Arch Linux for a few days now and sidebery drag and drop was working just fine with the latest version until I reinstalled it from scratch after the theme bugged out on me, and now I'm experiencing this issue.

**Comment by Duder963** [comment] 2024-06-29 10:23
Found a partial fix from [this bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1818517). Setting `widget.gtk.ignore-bogus-leave-notify=1` stops sidebery from closing on dragging a tab. However sidebery will not close upon leaving the hover area while dragging, and another window's sidebar will not expand. I still have no explanation for why it was working just fine for me a few days ago. For reference I'm using Hyprland

**Comment by Naezr** [comment] 2024-06-29 10:37
> Setting `widget.gtk.ignore-bogus-leave-notify=1` stops sidebery from closing on dragging a tab. 

It works and it really helps. When you change this setting, the behavior becomes the same as on Windows. I'll add it to `user.js`

> However sidebery will not close upon leaving the hover area while dragging, and another window's sidebar will not expand.

Yes, the behavior is the same on Windows, I checked it out

**Comment by Duder963** [comment] 2024-06-29 10:43
Did some more sleuthing. This regression(?) occurred between Hyprland 0.41.1 and 0.41.2. You say sidebery does not retract upon leaving its hover area on Windows, does this mean that is intended behavior? Because on 0.41.1 the sidebar does hover and unhover while dragging, and I can, for instance, move tabs between two windows

**Comment by Naezr** [comment] 2024-06-29 10:53
I would like to get behavior like yours, so that the cursor holding the tab just activates `:hover` as usual. I don't know if there is an intended behavior here. No one intended Firefox to work this way. It's possible that the fact that sidebar stays popped up on Windows (and Linux when you change that setting) is a bug.

**Closed** 2024-07-07 11:35 UTC
Labels: bug, help wanted
