### ISSUE TITLE
Drop-down box styling is a bit weird (and very bad on dark-mode)

### ISSUE THREAD

**Issue by nirurin** [Naezr/ShyFox#106] opened 2024-07-22 01:31 UTC
On 'light mode' (I never use light mode but still) it looks ok, though the oddly rounded little capsules and two-tone colour scheme seems to not fit with the rest of the colour scheme. However on dark mode (especially via dark-reader extension) it goes to a dark grey and (for some reason) bright white combination. 

I've noticed this on other sites too, but these shots are from parcel2go.com 

![Screenshot 2024-07-22 022814](https://github.com/user-attachments/assets/d36952ad-89f3-4d0a-8dd4-46554004dc98)
![Screenshot 2024-07-22 022826](https://github.com/user-attachments/assets/fd8028cc-9ee0-4a0f-b5f9-3926127d596f)

**Comment by Naezr** [comment] 2024-07-22 07:19
This website is inaccessible to me.

![image](https://github.com/user-attachments/assets/100e3fbf-68a9-46dd-9feb-d0dc8e953b8e)

 Check if the same issue is repeated here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

For me it looks like this:

![image](https://github.com/user-attachments/assets/72d4915e-4484-4368-907d-1c5d4dc0c68b)
![image](https://github.com/user-attachments/assets/b0f8cd40-fa5a-45a3-b080-0ef80a95aa21)

If not, then provide other examples

**Comment by nirurin** [comment] 2024-07-22 18:17
On that mozilla site it looks the same as yours. I'll see if I can find other site examples. 

The parcel2go site is a UK courier so you can probably access it via a vpn set to UK. But I'll try and find another example elsewhere too.

**Comment by Naezr** [comment] 2024-07-25 12:06
| Linux | Windows |
| --- | ---|
| ![image](https://github.com/user-attachments/assets/556b6384-3e1d-48ce-813b-e80a3858fe7b) | ![image](https://github.com/user-attachments/assets/4f10f8fe-bdba-4e3f-b54a-22d9e9ddb8da) |
| ![image](https://github.com/user-attachments/assets/c31a385e-5d69-4c34-87fb-62f0267761a0) | ![image](https://github.com/user-attachments/assets/ef647ced-b15a-4c47-b486-0259abb605ce) |

I can partially reproduce this issue on Windows. Still don't know what is this padding on the right on your screenshots

**Comment by Naezr** [comment] 2024-07-25 14:23
The fix is in the nightly branch now. The coloring should be fixed, but I don't know about  padding on the right.

Now this menu looks like this for me on Windows:
![image](https://github.com/user-attachments/assets/17448586-f752-488e-abd1-6fad30556148)![image](https://github.com/user-attachments/assets/18667b97-b796-454e-b9ad-215056e4f6cf)

**Closed** 2024-08-05 10:06 UTC
Labels: bug
